# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         WWW-Blog-Metadata-OpenID
version:      0.01
version_from: lib/WWW/Blog/Metadata/OpenID.pm
installdirs:  site
requires:
    Test::More:                    0.32
    WWW::Blog::Metadata:           0.02

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.27
